### ISSUE TITLE
kaggle kernel for load and extract image is not correct

### ISSUE THREAD

**Issue by nasif25** [damminhtien/Deep-Learning-Image-Caption-Generator#8]
I believe the kaggle kernel link you provided for loading image and extracting image is not correct. The link leads to a code that defines the data generator slight differently than the code you provided in your developing model kaggle kernel. Though I found that the notebook reference for handling image data does provide an answer on how you get photo features saved up in features.pkl. So, any researcher/learner should find their way to what they needed. I just pointed it out if you have not done this intentionally, you may check the kaggle kernel link for loading photo and extracting features.

**Comment by damminhtien** [comment]
@nasif25 Sr for my late reply. This is my mistakes. I changed wrong link to exact link. I appreciated your attention.
